name: chrome
on:
  workflow_dispatch:

jobs:
  test:
    name: install
    runs-on: ubuntu-latest
    steps:

    - name: check out
      uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 1

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - run: |
          cd ./puppeteer
          npm install
          node ./test.js
