name: go hello world
on:
  push:

jobs:

  hello-world:
    name: hello-world
    runs-on: ubuntu-latest
    steps:

    - name: check out
      uses: actions/checkout@v3.5.2
      with:
        fetch-depth: 1

    - name: install
      run: |
        cd go/hello-world && go build
        ./actions-playground-go-hello-world
