name: matrix with witnesses
on:
  push:

jobs:
  work:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        name: [alpha, beta]

    steps:
    - uses: actions/checkout@v2

    - name: env
      run: echo "commit-sha=$(echo ${GITHUB_SHA})" >> $GITHUB_ENV

    - run : echo "${{ matrix.name }}" > $GITHUB_WORKSPACE/witness-${{ matrix.name }}

    - name: record ${{ matrix.name }} witness
      id: witness
      uses: actions/cache@v2
      with:
        path: $GITHUB_WORKSPACE/witness-${{ matrix.name }}
        key: witness--${{ matrix.name }}--${{ env.commit-sha }}

    - name: work ${{ matrix.name }}
      id: work
      run: exit 1
      if: steps.witness.outputs.cache-hit != 'true'
