name: merge base
on:
  push:

jobs:

  merge-base:
    name: merge base
    runs-on: ubuntu-latest
    steps:

    - name: check out
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 1

    - run: git fetch --depth=1 origin main

    - name: run
      run: |
        # TODO
        echo "$GITHUB_REF"
        echo "$(git diff --name-only $GITHUB_REF $(git merge-base $GITHUB_REF origin/main))"
