name: merge base
on:
  push:

jobs:

  merge-base:
    name: merge base
    runs-on: ubuntu-latest
    steps:

    - name: check out
      uses: actions/checkout@v2.3.4

    - run: git fetch origin main

    - name: run
      run: |
        # TODO
        echo "$GITHUB_REF"
        echo "$(git status)"
        echo "$(git --no-pager branch)"
        echo "$(git merge-base $GITHUB_REF origin/main)"
        echo "$(git diff --name-only $GITHUB_REF $(git merge-base $GITHUB_REF origin/main))"
