name: open pr
on:
  workflow_dispatch:

jobs:

  open:
    name: open pr
    runs-on: ubuntu-latest
    steps:

    - name: check out
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 1

    - name: setup node
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 14

    - name: commit and open pr
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          echo "$(date)" > a-change
          branch_name="a-change--$(date +%s)"
          git checkout -b $branch_name
          git add .
          git commit -m "a change"
          git push --set-upstream origin $branch_name
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/romainmenke/actions-playground/pulls \
          -H "Authorization: token $GITHUB_TOKEN" \
          -d '{"head":"head","base":"main"}'
