name: open pr
on:
  workflow_dispatch:

jobs:

  open:
    name: open pr
    runs-on: ubuntu-latest
    steps:

    - name: check out
      uses: actions/checkout@v3.2.0
      with:
        fetch-depth: 1

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: commit and open pr
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          # Git config
          git config user.name github-actions
          git config user.email github-actions@github.com
          # a change
          echo "$(date)" > a-change
          # checkout a new branch
          branch_name="a-change--$(date +%s)"
          git checkout -b $branch_name
          git add .
          git commit -m "a change"
          # push
          git push --set-upstream origin $branch_name
          # open pr
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/romainmenke/actions-playground/pulls \
          -H "Authorization: token $GITHUB_TOKEN" \
          -d "{\"head\":\"$branch_name\",\"base\":\"main\",\"title\":\"a change\"}"
