name: pages
on:
  push:
    branches:
    - 'main'

jobs:

  fmt:
    name: pages
    runs-on: ubuntu-latest
    steps:

    - name: check out
      uses: actions/checkout@v2.3.2
      with:
        fetch-depth: 1

    - run: |
        git fetch --depth=1 origin pages || true

    - name: create pages content
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        tmpfile=$(mktemp /tmp/index.XXXXXXXXXX)
        echo "hello! $(date)" >> $tmpfile
        git checkout pages 2>/dev/null || git checkout -b pages
        rm -f ./index.html
        cp $tmpfile ./index.html
        git add .
        git commit -m "update pages"
        git push --set-upstream origin pages
