name: pages
on:
  push:
    branches:
    - 'main'

jobs:

  fmt:
    name: pages
    runs-on: ubuntu-latest
    steps:

    - name: check out
      uses: actions/checkout@v3.0.0
      with:
        fetch-depth: 1

    - run: |
        git fetch --depth=1 origin pages || true

    - name: create pages content
      run: |
        # Git config
        git config user.name github-actions
        git config user.email github-actions@github.com
        # Create some content
        tmpfile=$(mktemp /tmp/index.XXXXXXXXXX)
        echo "hello! $(date)" >> $tmpfile
        # Checkout pages branches
        git checkout pages 2>/dev/null || git checkout -b pages
        # Clean pages branch
        git ls-files -z | xargs -0 rm -f
        git ls-tree --name-only -d -r -z HEAD | sort -rz | xargs -0 rmdir || true
        # Copy contents
        mkdir ./docs
        cp $tmpfile ./docs/index.html
        # Submit
        git add .
        git commit -m "update pages"
        git push --set-upstream origin pages
