name: push vs. pull request
on:
  push:
    branches:
    - 'main'
  pull_request:

jobs:
  push-vs-pull-request:
    name: push vs. pull request
    runs-on: ubuntu-latest
    steps:
    - run: echo "push vs. pull request"

    - name: GITHUB_REF
    - run: git --no-pager diff --name-only $GITHUB_REF $(git merge-base $GITHUB_REF master)
      continue-on-error: true
