name: push vs. pull request
on:
  push:
  pull_request:

jobs:
  push-vs-pull-request:
    name: push vs. pull request
    runs-on: ubuntu-latest
    steps:
    - run: echo "push vs. pull request"

    - name: check out
      uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 1

    - run: git fetch

    - name: GITHUB_REF
      run: git --no-pager diff --name-only $GITHUB_REF $(git merge-base $GITHUB_REF main)
      continue-on-error: true

    - name: HEAD merge base
      run: git merge-base HEAD origin/main
      continue-on-error: true

    - name: HEAD diff
      run: git --no-pager diff --name-only HEAD $(git merge-base HEAD origin/main)
      continue-on-error: true
