name: push vs. pull request
on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  push-vs-pull-request:
    name: push vs. pull request
    runs-on: ubuntu-latest
    steps:
    - run: echo "push vs. pull request"

    - name: check out
      uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 1

    - run: git fetch origin $GITHUB_BASE_REF

    - run: git --no-pager diff --name-only origin/main

    - run: echo $GITHUB_BASE_REF
    - run: git merge-base --fork-point origin/$GITHUB_BASE_REF

    - name: GITHUB_REF diff
      run: git --no-pager diff --name-only $GITHUB_REF $(git merge-base --fork-point HEAD origin/main)
      continue-on-error: true

    - name: HEAD diff
      run: git --no-pager diff --name-only HEAD $(git merge-base --fork-point HEAD origin/main)
      continue-on-error: true
