name: install
on:
  push:
    paths:
    - '/**/*.js'
    - '/package.json'

jobs:

  fmt:
    name: install
    runs-on: ubuntu-latest
    steps:

    - name: check out
      uses: actions/checkout@v2.3.2
      with:
        fetch-depth: 1

    - name: setup node
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 14

    - run: ls ~/.npm
    - name: cache node modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('yarn.lock') }}
    - run: yarn install
    - run: yarn run postinstall
    - run: ls ~/.npm
