name: install
on:
  workflow_dispatch:
    inputs:
      run_index:
        description: 'Run Index'
        required: false
        default: "true"
  push:

jobs:

  fmt:
    name: install
    runs-on: ubuntu-latest
    steps:

    - name: env
      run: |
          echo "commit-sha=$(echo ${GITHUB_SHA})" >> $GITHUB_ENV

    - name: check out
      uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 1

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: set node version env
      run: |
          echo "node-version=$(node --version)" >> $GITHUB_ENV
          echo "yarn-cache-dir=$(yarn cache dir)" >> $GITHUB_ENV

    - run: echo "$GITHUB_SHA"
    - name: cache node modules
      uses: actions/cache@v3.0.2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: |
          ~/.npm
          js/node_modules
          ${{ env.yarn-cache-dir }}
        key: cache__${{ env.commit-sha }}__${{ runner.os }}__node-${{ env.node-version }}__npm-and-node-modules__${{ hashFiles('js/yarn.lock') }}
    - run: cd ./js && yarn install
    - run: node ./js/index.js
      if: ${{ github.event.inputs.run_index }}
