name: install
on:
  workflow_dispatch:
    inputs:
      run_index:
        description: 'Run Index'
        required: true
        default: false
  push:

jobs:

  fmt:
    name: install
    runs-on: ubuntu-latest
    steps:

    - name: check out
      uses: actions/checkout@v2.3.2
      with:
        fetch-depth: 1

    - name: setup node
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 14

    - name: set node version env
      run: echo ::set-env name=node-version::$(node --version)

    - name: cache node modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: |
          ~/.npm
          js/node_modules
        key: cache__${{ runner.os }}__node-${{ env.node-version }}__npm-and-node-modules__${{ hashFiles('js/yarn.lock') }}
    - run: cd ./js && yarn install
    - run: node ./js/index.js
      if: ${{ github.event.inputs.run_index }}
